### ISSUE TITLE
Group pads and pads per user

### ISSUE THREAD

**Issue by goldquest** [moodlehu/moodle-mod_etherpadlite#2]
Feature request:
- Group pads
- Pads per user

**Comment by eberhardt** [comment]
Any plans to implement it in the near future? ^^

**Comment by mlz-dev** [comment]
Hi Eberhardt,

since "Pads per user" does not make to much sense for us, as we see the main purpose for the etherpad-module in situations where two or more people are writing e.g. the minutes within the exact same time together, so i think we won't implement this.

If I get "Group pads" right, this would integrate the etherpad-module into the moodle's own group functionality, for which I see usecases, but since we don't have the manpower to do this right now,
unfortunately the answer is as above - No, not planned to be implemented yet.

Best Regards
Jens
