### ISSUE TITLE
views are not listest in the activity reports

### ISSUE THREAD

**Issue by moodlebeuth** [moodlehu/moodle-mod_etherpadlite#28]
Hello,

just a note: Stefanie and I discovered that the views of an etherpad activity are not listest in the activity reports (outline). I am using moodle 2.8.x, moodle-mod_etherpadlite (v. 2015021101) and etherpad lite (v. 1.5.6).

Thanks & Greetings,
Michael

**Comment by lucaboesch** [comment]
In fact, your plugin does not write to the logging system at all, does it?

**Comment by mlz-dev** [comment]
Hi Luca,

yes, you are right. The plugin does not write to the logging system at all by now. We could / should at least log adding an etherpad to the courses activities, since anything else (witing/text editing) is 
handled outside moodle by/through the etherpad installation an therefor invisible to moodle.

Best regards
Jens
