### ISSUE TITLE
Private Pads

### ISSUE THREAD

**Issue by fernandooliveira** [moodlehu/moodle-mod_etherpadlite#29]
Thanks for this great plugin. Can you tell me if it's possible to create private pads, which are only visible to teacher and individual student? Also, would you consider adding this plugin to the Moodle repository?

**Comment by goldquest** [comment]
Hi,
thanks for the interest in this plugin.
Private Pads are not possible at the moment. We have some requests to include Groups. Would that solve your problem?
This plugin is actually already in the Moodle Repository: https://moodle.org/plugins/mod_etherpadlite

**Comment by mlz-dev** [comment]
Hi Fernando,

we see the main purpose for the etherpad-module in situations where two or more people are writing e.g. the minutes within the exact same time together.

Integrate the etherpad-module into the moodle's own group functionality, is requested from time to time, but since we don't have the manpower to do this right now, unfortunately the answer is: "not planned to be implemented soon...."

Best regards
Jens
