### ISSUE TITLE
Support separate groups

### ISSUE THREAD

**Issue by porcospino** [moodlehu/moodle-mod_etherpadlite#34]
Hello

Is it possible to modify this plug-in so that Moodle groups can be used?  Looking at the Etherpad documentation, the HTTP API supports the creation of group pads:

https://github.com/ether/etherpad-lite/blob/master/doc/api/http_api.md

Thanks,

Chris

**Comment by grabs** [comment]
Hi Chris,

thank for your suggestion. I thought about it too. The plugin already uses group pads but that is not the point. There are some caveats.
* If we use different groups in one activity instance for each group a pad has to be created.
* If a new group is created I have to create a new pad for this new group. So I must observe the group creation.
* If a group is deleted what shall I do with the pad? Should I delete the pad of this group and all the work is gone? In any case I must observe the deletion of groups.
* What is if a user switches the group? What should happen with the content he already created in the pad from the first group?

It might be a good solution for you if you just use the availability feature and create separate instances for each group and make them available only for the group you want.

Best regards
Andreas

**Comment by elearning-dev-univie** [comment]
Hi. As you can see, we have implemented this feature and would be happy to provide to everyone in the community.
These are the answers to your questions and how we implemented it:
If we use different groups in one activity instance for each group a pad has to be created.
-> done

If a new group is created I have to create a new pad for this new group. So I must observe the group creation.
-> done

If a group is deleted what shall I do with the pad? Should I delete the pad of this group and all the work is gone? In any case I must observe the deletion of groups.
-> We implemented a deletion mechanism, which deletes the pad after a certain amount of time (e.g. if somebody accidentally disabled the group mode) This time can be changed in the settings.

What is if a user switches the group? What should happen with the content he already created in the pad from the first group?
-> If the user switches groups he doesn't have access to the old pad anymore. This is compliant with how it works e.g. in the forums. If the user is in multiple groups there is a selection where you can change which group pad you want to see. This also is according to how it works in the forums. We thought since moodle solved it that way, we should stick to this solution since they thought about it and the users are used to this behavior.

If there are any questions feel free to ask. We are happy to answer the questions and would be grateful to get this feature into the core of your plugin.

**Comment by grabs** [comment]
The support of separate groups has been integrated.
Thanks to Thomas Wedekind of the University of Vienna.
