### ISSUE TITLE
Optional export of pads

### ISSUE THREAD

**Issue by andremenrath** [moodlehu/moodle-mod_etherpadlite#46]
We at Graz University developed a local plugin, which adds a button for teachers and managers for copying the pads-link to the clipboard for example to provide an easy way for adding the pad manually as a widget in a matrix-chatroom.

Would you maybe be interested in merging this functionality as an optional feature? Then I would provide a pull request for this.

**Comment by grabs** [comment]
Hi, thank your for this suggestion! Could you describe what pad-link exactly do you mean?
If you're talking about the iframe-src, this should be possible in general. But it won't work in most cases because you need a login session in Moodle to access the pad. It would work if users aren't required to authenticate to your etherpad and your pads are openly accessible.
Best regards
Andreas

**Comment by andremenrath** [comment]
Hello, yes I meant the iframe-src. Whether the place this link is used has access or not is of course not in the scope of this :) Greetings, André
